DATASET:
  root_dataset: "./data/"
  list_train: "./data/val_10.odgt"
  list_val: "./data/val_10.odgt"
  num_class: 150
  imgSizes: (300, 375, 450)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 21
  start_epoch: 20
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 1
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_21.pth"

TEST:
  checkpoint: "epoch_21.pth"
  result: "./"

DIR: "ckpt/test"
